
export const home_details = {
    
    hairdryer:false,
    hot_water:false,
    toilet_paper:false,
    washing_machine:false,
    dryer:false,
    iron:false,
    crib:false,
    chair_baby:false,
    box_baby:false,
    fireplace:false,
    air_conditioning:false,
    electric_fan:false,
    tv:false,
    refrigerator:false,
    microware:false,
    plate:false,
    pot:false,
    coffee_machine:false,
    wifi:false,
    balcony:false,
    courtyard:false,
    outdoor_food:false,
    barbecue:false,
    outdoor_forniture:false,
    parking:false,
    animal:false,
    smoke:false,
    reception:false,
    fire_prevention:false,
    monoxide:false
}