services:
  app:
    build: ./client
    ports:
      - 4200:4200
    volumes:
      - ./client/src:/app/src

  server:
    build: ./server
    ports:
      - 3700:3700
    environment:
      DB_URL: mongodb://db/holiday
    volumes:
      - ./server:/app/
      - /app/node_modules  
    command: npm start
    depends_on:
      - db
  
  db:
    image: mongo:5.0.19-focal
    ports:
      - 27017:27017
    volumes:
      - holiday:/data/db

volumes:
  holiday: